specfile_path: colin.spec
synced_files:
  - colin.spec
  - .packit.yaml
upstream_package_name: colin
downstream_package_name: colin
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
